try 
{
	// ${1:try_code}
}
catch (Exception $${2:exception})
{
	// ${3:catch_code}
}
${4}
